title: Hyttebrygga - et bryggesystem fra BubbleDock
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: ''
layout: boxed
style: classic
palette: green
mode: light
base_font: serif
header:
  title: Hyttebrygga
  has_primary_nav: true
  primary_nav_links:
    - label: Pricing
      url: /pricing
      style: link
    - label: About
      url: /about
      style: link
    - label: Style Guide
      url: /style-guide
      style: link
  has_secondary_nav: false
  secondary_nav_links:
    - label: Get Started
      url: /pricing
      style: primary
  has_anncmnt: false
  anncmnt_content: >-
    Curabitur ac tellus mattis, tempor ipsum eu, eleifend sapien. **[Learn
    More](/pricing/)**
  anncmnt_align: left
  anncmnt_is_home_only: false
  anncmnt_has_close: true
  anncmnt_id: new-features
footer:
  has_primary_nav: false
  primary_nav_title: Informasjon
  primary_nav_links:
    - label: About
      url: /about
      style: link
  has_secondary_nav: true
  secondary_nav_title: Blog
  secondary_nav_links:
    - label: News
      url: /blog/category/news
      style: link
    - label: General
      url: /blog/category/general
      style: link
    - label: Tutorials
      url: /blog/category/tutorials
      style: link
  has_tertiary_nav: true
  tertiary_nav_title: Legal
  tertiary_nav_links:
    - label: Terms & Conditions
      url: /terms-conditions
      style: link
    - label: Privacy Policy
      url: /privacy-policy
      style: link
  has_social: true
  social_links:
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: link
      has_icon: true
      icon: linkedin
      icon_position: center
      new_window: true
    - label: LinkedIn
      url: 'https://www.youtube.com/'
      style: link
      has_icon: true
      icon: youtube
      icon_position: center
      new_window: true
    - label: LinkedIn
      url: 'https://vimeo.com/'
      style: link
      has_icon: true
      icon: vimeo
      icon_position: center
      new_window: true
  content: '&copy; Stackbit-DIY. All rights reserved.'
  links:
    - label: Made with Stackbit.
      url: 'https://www.stackbit.com'
      style: link
sass:
  indentWidth: 4
  style: expanded
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
